# tasks file
---

- import_tasks: "{{ role_path }}/tasks/setup_install.yml"
  when: ms_rstudio_enabled|bool
  tags:
    - setup-all
    - setup-ms-rstudio
    - setup-ms-develall

- import_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
  when: not ms_rstudio_enabled|bool
  tags:
    - setup-all
    - setup-ms-rstudio
    - setup-ms-develall


