- name: uninstalling rstudio teaching stuff
  file:
    path: '{{item}}'
    state: absent
  with_items:
    - '{{ansible_env.HOME}}/.local/share/applications/rstudio_teaching.desktop'
    - '{{ansible_env.HOME}}/bin/rstudio_teaching'

- name: remove
  apt:
    name: rstudio
    state: absent
  become: yes

- name: remove | create (download) directory
  file:
    path: "{{ rstudio_downloads_path }}"
    state: absent
